name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_hisat2.yaml --lint"
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Formatting
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: featurecount
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test workflow (hisat2)
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_hisat2.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    - name: Test workflow (salmon)
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_salmon.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    - name: Test workflow (star)
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_star.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    - name: Test workflow (bwamem2)
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_bwamem2.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    - name: Test workflow (bowtie2)
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_bowtie2.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"

